
import { Inter } from "next/font/google";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FileIcon, StarIcon } from "lucide-react";
import { SideNav } from "./side-nav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12">
    <div className="flex gap-10">
        <SideNav/>
      <div className="w-full">
      {children}
     </div>
      </div>
  </main>
  );
}